export const ResponseCode = {
  OK: "OK",
  ERROR: "ERROR",
  NOT_FOUND: "NOT_FOUND",
  NOT_APPROVED: "NOT_APPROVED",
  UNAUTHORIZED: "UNAUTHORIZED",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR"
}
